### ISSUE TITLE
Generate *.tif based in reclassification

### ISSUE THREAD

**Issue by SuelenRuiz** [SMByC/ThRasE#4]
Is there a way to export a tif based in the reclassification that I did? Each image that I reclassify I would like to do this, if possible.
Another thing is: *.yml is only a extension that save the color of the classes?
I really liked the plugin!
Thanks in advance.

**Comment by XavierCLL** [comment]
Hi @SuelenRuiz 

I'm not sure if I understand your question... the plugin edit the layer on the fly, it means that every reclassification that you do is saved in the tif that you are editing (save in disk) you don't need at the end od reclassification to save the changes that you have done because it overwrites the file every time. If you need to reclassify the same file with different edition, create a copy of it.

On the other hand, the .yml saves all the settings of the plugin: the layers loaded, recode table, navigation, options...

Regards,
Xavier
